### ISSUE TITLE
Error while running the testing on an image

### ISSUE THREAD

**Issue by dreamstorm25** [piperod/beepose#2]
I tried using the model I have trained but I get the following error while running the process_folder_images.py - 
"Dimension 0 in both shapes must be equal, but are 1 and 28. Shapes are [1,1,512,12] and [28,512,1,1]. for 'Assign_40' (op: 'Assign') with input shapes: [1,1,512,12], [28,512,1,1]."
Here is the stack trace
Traceback (most recent call last):
  File "/home/mrwick/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1 and 28. Shapes are [1,1,512,12] and [28,512,1,1]. for 'Assign_40' (op: 'Assign') with input shapes: [1,1,512,12], [28,512,1,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mrwick/beepose/beepose/inference/process_folder_image.py", line 61, in <module>
    model.load_weights(keras_weights_file)
  File "/home/mrwick/venv/lib/python3.6/site-packages/keras/engine/topology.py", line 2645, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/home/mrwick/venv/lib/python3.6/site-packages/keras/engine/topology.py", line 3166, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/mrwick/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2365, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/mrwick/venv/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1762, in assign
    name=name)
  File "/home/mrwick/venv/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/home/mrwick/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/home/mrwick/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/mrwick/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/mrwick/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/mrwick/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/home/mrwick/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 28. Shapes are [1,1,512,12] and [28,512,1,1]. for 'Assign_40' (op: 'Assign') with input shapes: [1,1,512,12], [28,512,1,1].

**Comment by piperod** [comment]
Hi @dreamstorm25 thanks for using the code. What script are you using for inference?

**Comment by dreamstorm25** [comment]
beepose/inference/process_folder_image.py
Also will the code also produces images with keypoints drawn on it or just produce a json file ?

**Comment by piperod** [comment]
There are two things. 12 is the default number of pafs, but seems that you are using 28?... Are you using the latest version? (I pushed yesterday) If that's the case, make sure you are pointing to the right config file. In fact, could you provide the full command line that you are using? The second thing is that it seems its transposed in your case, which is odd. Maybe you modified something else during training?

**Comment by dreamstorm25** [comment]
My dataset has 13 keypoints so its correct that np2 = 14 and np1 = 28, right ? I did not have the latest version. When I ran the latest version the above error did not occur, but it gave some other error. Closing this issue and will raise another issue for that.
